server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api-customers/v1/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api-products/v1/**
        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/api-invoices/**
